### ISSUE TITLE
Is it possible to somehow access a different context?

### ISSUE THREAD

**Issue by danonline** [TingPing/hexchat-javascript#6]
I would like to execute a command in a certain context from another context. For example if I type !test in context A, I want something to happen in context B. From what I have read, this is possible in the [Python Interface](http://hexchat.readthedocs.org/en/latest/script_python.html#context-objects), but I can't get it to work with JavaScript. The context is always undefined. Am I doing something wrong or does the JavaScript Interface not support context objects (the feature list states "Full coverage of hexchat api", so I'm not sure if context is a part of the API)?

This is a snippet of the code I tried.
```javascript
function twitchWhisper(nick, msg) {
  var channels = get_list('channels');
  var server, channel, cnc;
  for(var c in channels) {
    if(channels[c].network == 'Twitch group chat' && channels[c].type == 2) {
      cnc = channels[c].context; // is undefined
      server = channels[c].server;
      channel = channels[c].channel;
      break;
    }
  }
  cnc = find_context(server, channel); // returns undefined
  cnc.command('PRIVMSG #jtv :/w ' + nick + ' ' + msg); // results in an error
}
```

**Comment by TingPing** [comment]
`find_context()` and `set_context()` should work for now, the list objects don't expose the context directly like Python which would be nice.
